version: '2'

volumes:
  postgres:
    driver: local
  solr:
    driver: local
  fcrepo:
    driver: local
  redis:
    driver: local
  streaming:
    driver: local
  work:
    driver: local

services:
  db:
    image: postgres:9.6-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: IdontCare
      POSTGRES_USER: avalon
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  fcrepo:
    image: ualbertalib/docker-fcrepo4
    volumes:
      - fcrepo:/fcrepo4-data
    ports:
      - "8984:8080"
  solr:
    image: solr:6.6
    ports:
      - "8983:8983"
    volumes:
      - solr:/opt/solr/server/solr/mycores
      - ./solr/config:/config
      - ./solr/scripts/solr-precreate-avalon.sh:/docker-entrypoint-initdb.d/solr-precreate-avalon.sh
  matterhorn:
    image: avalonmediasystem/matterhorn
    volumes:
      - ./masterfiles:/masterfiles
      - streaming:/streamfiles
      - work:/work
    ports:
      - "8080:8080"
  hls:
    image: avalonmediasystem/nginx
    volumes:
      - streaming:/data
    ports:
       - "8880:80"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
