default: &default
  url: <%= Rails.application.secrets.solr_url %>
  adapter: solr
development:
  url: <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/avalon_development' %>
  adapter: solr
test:
  url: <%= ENV['SOLR_TEST_URL'] || 'http://localhost:8983/solr/avalon_test' %>
  adapter: solr
uat:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
